version: '3'
services:
  envoy:
    build:
      context: envoy
    ports:
      - "8080:8080"
      - "9090:9090"
  first:
    build:
      context: first
    environment:
      - SVC_TARGET_URL=http://envoy:8080/second
  second:
    build:
      context: second
